controller_manager:
  ros__parameters:
    update_rate: 100
    sue_sim_time: true

    arm_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    command_interface:
      - position

    state_interface:
      - position
      - velocity
